Update aquasec.yml

diff --git a/.github/workflows/aquasec.yml b/.github/workflows/aquasec.yml
--- a/.github/workflows/aquasec.yml
+++ b/.github/workflows/aquasec.yml
@@ -19,6 +19,7 @@ jobs:
               ls -l / &&
               git config --global --add safe.directory /github/workspace
 
+
       - name: Run Aqua scanner
         uses: docker://aquasec/aqua-scanner
         with:
@@ -35,3 +36,31 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
           TRIVY_RUN_AS_PLUGIN: 'aqua'
           # For http/https proxy configuration add env vars: HTTP_PROXY/HTTPS_PROXY, CA-CRET (path to CA certificate)
+
+
+      - name: Build docker image
+        run: sudo docker build -t aquasupportemea/insecure-bank-app:${{ github.sha }} .
+
+
+      - name: SBOM Generation
+        run: |
+          export BILLY_SERVER=https://billy.codesec.aquasec.com
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum ; then
+          echo "install.sh checksum failed"
+          exit 1
+          fi
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          ./billy generate \
+            --access-token "${{ secrets.GH_TOKEN }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --artifact-path "aquasupportemea/insecure-bank-app:${{ github.sha }}"
+
+            # The docker image name:tag of the newly built image
+            # --artifact-path "my-image-name:${{ env.tag-version }}" 
+            # OR the path to the root folder of your project. I.e my-repo/my-app 
+            ## --artifact-path "${{env.MY_APP_ROOT}}"
+        
