Update aquasec.yml

diff --git a/.github/workflows/aquasec.yml b/.github/workflows/aquasec.yml
--- a/.github/workflows/aquasec.yml
+++ b/.github/workflows/aquasec.yml
@@ -13,9 +13,17 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Run First Pipeline
-        run: |
-          # Your first pipeline steps go here
+      - name: Aqua code scanning (SCA,IaC and SAST)
+        uses: docker://aquasec/aqua-scanner
+        with:
+          args: trivy fs --scanners config,vuln,secret --sast .
+        env:
+          ENABLE_TRIVY_STDOUT: 'true'
+          AQUA_KEY: ${{ secrets.AQUA_KEY }}
+          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+          TRIVY_RUN_AS_PLUGIN: 'aqua'
+
 
   second_pipeline:
     needs: first_pipeline
@@ -25,6 +33,22 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Run Second Pipeline
+      - name: Build docker image
+        run: sudo docker build -t aquasupportemea/insecure-bank-app:${{ github.sha }} .
+      
+      - name: SBOM Generation
         run: |
-          # Your second pipeline steps go here
+          export BILLY_SERVER=https://billy.codesec.aquasec.com
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum ; then
+          echo "install.sh checksum failed"
+          exit 1
+          fi
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          ./billy generate \
+            --access-token "${{ secrets.GH_TOKEN }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --artifact-path "aquasupportemea/insecure-bank-app:${{ github.sha }}"
