Update aquasec.yml

diff --git a/.github/workflows/aquasec.yml b/.github/workflows/aquasec.yml
--- a/.github/workflows/aquasec.yml
+++ b/.github/workflows/aquasec.yml
@@ -76,22 +76,22 @@ jobs:
 #      - name: Docker Image Push
 #        run: sudo docker push aquasupportemea/insecure-bank-app:${{ github.sha }}  
           
-      - name: SBOM Generation
-        run: |
-          # export BILLY_SERVER=https://billy.codesec.aquasec.com
-          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-          if ! cat install.sh.checksum | sha256sum ; then
-          echo "install.sh checksum failed"
-          exit 1
-          fi
-          BINDIR="." sh install.sh
-          rm install.sh install.sh.checksum
-          ./billy generate \
-            --access-token "${{ github.token }}" \
-            --aqua-key "${{ secrets.AQUA_KEY }}" \
-            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-            --artifact-path "aquasupportemea/insecure-bank-app:${{ github.sha }}"
+#      - name: SBOM Generation
+#        run: |
+#          export BILLY_SERVER=https://billy.codesec.aquasec.com
+#          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+#          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+#          if ! cat install.sh.checksum | sha256sum ; then
+#          echo "install.sh checksum failed"
+#          exit 1
+#          fi
+#          BINDIR="." sh install.sh
+#          rm install.sh install.sh.checksum
+#          ./billy generate \
+#            --access-token "${{ github.token }}" \
+#            --aqua-key "${{ secrets.AQUA_KEY }}" \
+#            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+#            --artifact-path "aquasupportemea/insecure-bank-app:${{ github.sha }}"
 
             # The docker image name:tag of the newly built image
             # --artifact-path "my-image-name:${{ env.tag-version }}" 
